# Site settings

title: 'LA Referencia - Soporte técnico DSpace'
title_pt: 'LA Referencia - Suporte técnico DSpace'

description: 'Portal de soporte técnico DSpace · Programa LA Referencia – Lyrasis'
description_pt: 'Portal de suporte técnico DSpace · Programa LA Referencia – Lyrasis'

baseurl: ''
absolute_url: 'https://example.com/'
url: 'https://example.com'

email: soporte@lareferencia.redclara.net
twitter_username: ''
github_username: ''

default_language: 'es'
fallback_page: 'home'

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
page_excerpts: true
excerpt_separator: <!--more-->
sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div

# Pages settings
include: ['_pages']
exclude:
  - _pages/en
  - _posts/en

collections:
  pages:
    output: true
    permalink: /:path

# Post defaults by language
defaults:
-
  scope:
    path: '_posts/es'
    type: 'posts'
  values:
    permalink: 'es/:title'
    language: es
-
  scope:
    path: '_posts/pt'
    type: 'posts'
  values:
    permalink: 'pt/:title'
    language: pt
