title: 'LA Referencia - Soporte técnico DSpace'
title_en: 'LA Referencia - Technical support DSpace'
title_pt: 'LA Referencia - Suporte técnico DSpace'

description: 'Portal de soporte técnico DSpace · Programa LA Referencia – Lyrasis'
description_en: 'Technical support portal DSpace · LA Referencia – Lyrasis Program'
description_pt: 'Portal de suporte técnico DSpace · Programa LA Referencia – Lyrasis'

baseurl: ''
url: 'https://example.com'
absolute_url: 'https://example.com'

email: soporte-dspace@lareferencia.info
github_username: ''

default_language: 'es'
fallback_page: 'home'

theme: minima
markdown: kramdown
page_excerpts: true
excerpt_separator: <!--more-->
sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div

include: ['_pages']
collections:
  pages:
    output: true
    permalink: /:path

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/:title'
    language: en
- scope:
    path: '_posts/es'
    type: 'posts'
  values:
    permalink: 'es/:title'
    language: es
- scope:
    path: '_posts/pt'
    type: 'posts'
  values:
    permalink: 'pt/:title'
    language: pt
